name: "Tests"
on:
  pull_request:
    branches: [latest]
  push:
    branches: [latest]
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - run: nix-shell --command "cargo test"
